//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a Chugin boilerplate, generated by chugerate!
//-----------------------------------------------------------------------------

// this should align with the correct versions of these ChucK files
#include "chuck_dl.h"
#include "chuck_def.h"

// general includes
#include <stdio.h>
#include <limits.h>
#include <cmath>

// declaration of chugin constructor
CK_DLL_CTOR(disto_ctor);
// declaration of chugin desctructor
CK_DLL_DTOR(disto_dtor);

// example of getter/setter
CK_DLL_MFUN(disto_setParam);
CK_DLL_MFUN(disto_getParam);
CK_DLL_MFUN(disto_setGain_in);
CK_DLL_MFUN(disto_getGain_in);

// for Chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK(disto_tick);

// this is a special offset reserved for Chugin internal data
t_CKINT disto_data_offset = 0;


// class definition for internal Chugin data
// (note: this isn't strictly necessary, but serves as example
// of one recommended approach)
class disto
{
public:
    // constructor
    disto( t_CKFLOAT fs)
    {
        m_param = 0;
        gain_in = 0;
    }

    // for Chugins extending UGen
    SAMPLE tick( SAMPLE in )
    {
				if (gain_in == 0)
						return in;
				else
					  return std::atan (gain_in * in);
    }

    // set parameter example
    float setParam( t_CKFLOAT p )
    {
        m_param = p;
        return p;
    }

    // get parameter example
    float getParam() { return m_param; }
    
    // set parameter example
    float setGain_in( t_CKFLOAT p )
    {
        gain_in = p;
        return p;
    }

    // get parameter example
    float getGain_in() { return gain_in; }
    
private:
    // instance data
    float m_param;
    float gain_in;
};


// query function: chuck calls this when loading the Chugin
// NOTE: developer will need to modify this function to
// add additional functions to this Chugin
CK_DLL_QUERY( disto )
{
    // hmm, don't change this...
    QUERY->setname(QUERY, "disto");
    
    // begin the class definition
    // can change the second argument to extend a different ChucK class
    QUERY->begin_class(QUERY, "disto", "UGen");

    // register the constructor (probably no need to change)
    QUERY->add_ctor(QUERY, disto_ctor);
    // register the destructor (probably no need to change)
    QUERY->add_dtor(QUERY, disto_dtor);
    
    // for UGen's only: add tick function
    QUERY->add_ugen_func(QUERY, disto_tick, NULL, 1, 1);
    
    // NOTE: if this is to be a UGen with more than 1 channel, 
    // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
    // and declare a tickf function using CK_DLL_TICKF

    // example of adding setter method
    QUERY->add_mfun(QUERY, disto_setParam, "float", "param");
    // example of adding argument to the above method
    QUERY->add_arg(QUERY, "float", "arg");

    // example of adding getter method
    QUERY->add_mfun(QUERY, disto_getParam, "float", "param");
    
    // example of adding setter method
    QUERY->add_mfun(QUERY, disto_setGain_in, "float", "gain_in");
    // example of adding argument to the above method
    QUERY->add_arg(QUERY, "float", "arg");

    // example of adding getter method
    QUERY->add_mfun(QUERY, disto_getGain_in, "float", "gain_in");
    
    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    disto_data_offset = QUERY->add_mvar(QUERY, "int", "@d_data", false);

    // end the class definition
    // IMPORTANT: this MUST be called!
    QUERY->end_class(QUERY);

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the constructor
CK_DLL_CTOR(disto_ctor)
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT(SELF, disto_data_offset) = 0;
    
    // instantiate our internal c++ class representation
    disto * bcdata = new disto(API->vm->get_srate());
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT(SELF, disto_data_offset) = (t_CKINT) bcdata;
}


// implementation for the destructor
CK_DLL_DTOR(disto_dtor)
{
    // get our c++ class pointer
    disto * bcdata = (disto *) OBJ_MEMBER_INT(SELF, disto_data_offset);
    // check it
    if( bcdata )
    {
        // clean up
        delete bcdata;
        OBJ_MEMBER_INT(SELF, disto_data_offset) = 0;
        bcdata = NULL;
    }
}


// implementation for tick function
CK_DLL_TICK(disto_tick)
{
    // get our c++ class pointer
    disto * c = (disto *) OBJ_MEMBER_INT(SELF, disto_data_offset);
 
    // invoke our tick function; store in the magical out variable
    if(c) *out = c->tick(in);

    // yes
    return TRUE;
}


// example implementation for setter
CK_DLL_MFUN(disto_setParam)
{
    // get our c++ class pointer
    disto * bcdata = (disto *) OBJ_MEMBER_INT(SELF, disto_data_offset);
    // set the return value
    RETURN->v_float = bcdata->setParam(GET_NEXT_FLOAT(ARGS));
}


// example implementation for getter
CK_DLL_MFUN(disto_getParam)
{
    // get our c++ class pointer
    disto * bcdata = (disto *) OBJ_MEMBER_INT(SELF, disto_data_offset);
    // set the return value
    RETURN->v_float = bcdata->getParam();
}

// example implementation for setter
CK_DLL_MFUN(disto_setGain_in)
{
    // get our c++ class pointer
    disto * bcdata = (disto *) OBJ_MEMBER_INT(SELF, disto_data_offset);
    // set the return value
    RETURN->v_float = bcdata->setGain_in(GET_NEXT_FLOAT(ARGS));
}


// example implementation for getter
CK_DLL_MFUN(disto_getGain_in)
{
    // get our c++ class pointer
    disto * bcdata = (disto *) OBJ_MEMBER_INT(SELF, disto_data_offset);
    // set the return value
    RETURN->v_float = bcdata->getGain_in();
}
