Machine.add( "../EFFECTS/note_info.ck");
Machine.add( "../EFFECTS/note_info_rx.ck");
Machine.add( "../EFFECTS/note_info_tx.ck");
Machine.add( "../EFFECTS/ST.ck");
Machine.add( "../include/global_data.ck" );
Machine.add( "../include/global_mixer.ck" );
Machine.add( "../include/global_event.ck" );
Machine.add( "../include/synt_interface.ck" );

//Machine.add( "../seq_decode/seq_decode.ck" );
//Machine.add( "../part_decode/part_decode_new.ck" );
Machine.add( "../nanomidi_5.ck" );
Machine.add( "../lpd8/lpd8.ck" );
//Machine.add("../include/data_updater.ck");
Machine.add( "../include/end.ck" );
Machine.add( "../include/killer.ck" );
Machine.add( "../save/SAVE.ck" );
Machine.add( "../SYNC/SYNC.ck" );

Machine.add( "../launcher/launcher_hold.ck" );

me.yield();
Machine.add( "../SYNTA/SYNTA.ck" );

Machine.add("../VCF_LPF_light.ck");
Machine.add("../chord/chord.ck");
Machine.add( "../digit.ck" );
//Machine.add( "../scales/scales.ck");
Machine.add( "../sampler/sampler.ck");
Machine.add( "../EFFECTS/DUCK_MASTER.ck");
Machine.add( "../EFFECTS/CONTROL.ck");
Machine.add( "../EFFECTS/REV0.ck");
Machine.add( "../EFFECTS/REV1.ck");
Machine.add( "../EFFECTS/REC.ck");
Machine.add( "../NANOKONTROL/NANO.ck");

Machine.add( "../seq_3/ACTION.ck");
Machine.add( "../seq_3/ELEMENT.ck");

Machine.add( "../include/SIN.ck");

me.yield();
Machine.add( "../lpk25/lpk25.ck"); 
//Machine.add("../seq_2/top_seq.ck");
//Machine.add("../seq_2/seq.ck");
//Machine.add("../seq_2/seqSndBuf.ck");
//Machine.add("../seq_2/freq.ck");
//Machine.add("../seq_2/freq2.ck");
//Machine.add("../seq_2/seq_script.ck");
Machine.add("../break/break.ck");
Machine.add("../lpd8/lpd8_master.ck");
Machine.add("../EFFECTS/DUCK.ck");

Machine.add( "../seq_3/SEQ3.ck");
Machine.add( "../seq_3/WAV.ck");
me.yield();
Machine.add( "../seq_3/MASTER_SEQ3.ck");

Machine.add( "../EFFECTS/CONTROLER.ck");

// SYNTA
Machine.add("../SYNTA/GLIDE.ck");
Machine.add("../SYNTA/POLY.ck");


// SYNT
Machine.add("../SYNT/SUPERSAW0.ck");
Machine.add("../SYNT/SUPERSAW1.ck");
Machine.add("../SYNT/SUPERSAW2.ck");
Machine.add("../SYNT/SUPERSAW3.ck");
Machine.add("../SYNT/SUPERSAW4.ck");
Machine.add("../SYNT/SUPERSAW5.ck");
Machine.add("../SYNT/CHILL.ck");
Machine.add("../SYNT/HORROR.ck");
Machine.add("../SYNT/GRAIN.ck");
Machine.add("../SYNT/TB303.ck");
Machine.add("../SYNT/TB303C.ck");
Machine.add("../SYNT/MOD.ck");
Machine.add("../SYNT/STRINGBASS.ck");
Machine.add("../SYNT/AMBIENT.ck");
Machine.add("../SYNT/AMBIENT2.ck");
Machine.add("../SYNT/RESYNT.ck");
Machine.add("../SYNT/PSYBASS0.ck");
Machine.add("../SYNT/PSYBASS1.ck");
Machine.add("../SYNT/PSYBASS2.ck");
Machine.add("../SYNT/PSYBASS3.ck");
Machine.add("../SYNT/PSYBASS4.ck");
Machine.add("../SYNT/PSYBASS5.ck");
Machine.add("../SYNT/PSYBASS6.ck");
Machine.add("../SYNT/PSYBASS7.ck");
Machine.add("../SYNT/PSYBASS8.ck");
Machine.add("../SYNT/PSYBASS9.ck");
Machine.add("../SYNT/PSYBASS10.ck");
Machine.add("../SYNT/PSYBASS11.ck");
Machine.add("../SYNT/HPSYBASS0.ck");
Machine.add("../SYNT/MOD0.ck");
Machine.add("../SYNT/MOD1.ck");
Machine.add("../SYNT/MOD2.ck");
Machine.add("../SYNT/MOD3.ck");
Machine.add("../SYNT/MOD4.ck");
Machine.add("../SYNT/MOD5.ck");
Machine.add("../SYNT/MOD6.ck");
Machine.add("../SYNT/HMOD0.ck");
Machine.add("../SYNT/HMOD1.ck");
Machine.add("../SYNT/DUBBASS0.ck");
Machine.add("../SYNT/DUBBASS1.ck");
Machine.add("../SYNT/DUBBASS2.ck");
Machine.add("../SYNT/DUBBASS3.ck");
Machine.add("../SYNT/PLOC0.ck");
Machine.add("../SYNT/PLOC1.ck");
Machine.add("../SYNT/PLOC2.ck");
Machine.add("../SYNT/PLOC3.ck");
Machine.add("../SYNT/FROG0.ck");
Machine.add("../SYNT/FROG1.ck");
Machine.add("../SYNT/FROG2.ck");
Machine.add("../SYNT/FROG3.ck");
Machine.add("../SYNT/FROG4.ck");
Machine.add("../SYNT/NOISE0.ck");
Machine.add("../SYNT/NOISE1.ck");
Machine.add("../SYNT/NOISE2.ck");
Machine.add("../SYNT/NOISE3.ck");
Machine.add("../SYNT/NOISE4.ck");
Machine.add("../SYNT/AMB0.ck");
Machine.add("../SYNT/AMB1.ck");
Machine.add("../SYNT/AMB2.ck");
Machine.add("../SYNT/AMB3.ck");
Machine.add("../SYNT/AMB4.ck");
Machine.add("../SYNT/AMB5.ck");
Machine.add("../SYNT/AMB6.ck");
Machine.add("../SYNT/AMB7.ck");
Machine.add("../SYNT/AMB8.ck");
Machine.add("../SYNT/AMB9.ck");
Machine.add("../SYNT/AMB10.ck");
Machine.add("../SYNT/AMB11.ck");
Machine.add("../SYNT/SERUM0.ck");
Machine.add("../SYNT/PAD0.ck");
Machine.add("../SYNT/PAD1.ck");
Machine.add("../SYNT/PAD2.ck");
Machine.add("../SYNT/PAD3.ck");
Machine.add("../SYNT/VIOLIN0.ck");
Machine.add("../SYNT/VIOLIN1.ck");
Machine.add("../SYNT/CELLO0.ck");
Machine.add("../SYNT/VOICEA0.ck");
Machine.add("../SYNT/VOICEA1.ck");
Machine.add("../SYNT/VOICEA2.ck");

// STEREO EFFECTS
Machine.add("../EFFECTS/LPF_ST.ck");
Machine.add("../EFFECTS/STECHO.ck");
Machine.add("../EFFECTS/STREV1.ck");
Machine.add("../EFFECTS/STAUTOPAN.ck");
Machine.add( "../EFFECTS/STDUCKMASTER.ck");
Machine.add( "../EFFECTS/STDUCK.ck");
Machine.add( "../EFFECTS/STDIGIT.ck");
Machine.add( "../EFFECTS/STECHOC.ck");
Machine.add( "../EFFECTS/STECHOC0.ck");
Machine.add( "../EFFECTS/STECHOLHPFC.ck");
Machine.add( "../EFFECTS/STLPFC.ck");
Machine.add( "../EFFECTS/STLHPFC.ck");
Machine.add( "../EFFECTS/STBPFC.ck");
Machine.add( "../EFFECTS/STHPFC.ck");
Machine.add( "../EFFECTS/STBRFC.ck");
Machine.add( "../EFFECTS/STRESC.ck");
Machine.add( "../EFFECTS/STLPF.ck");
Machine.add( "../EFFECTS/STBPF.ck");
Machine.add( "../EFFECTS/STHPF.ck");
Machine.add( "../EFFECTS/STBRF.ck");
Machine.add( "../EFFECTS/STRES.ck");
Machine.add( "../EFFECTS/STWPDiodeLadder.ck");
Machine.add( "../EFFECTS/STWPKorg35.ck");
Machine.add( "../EFFECTS/STGAINC.ck");
Machine.add( "../EFFECTS/STGAIN.ck");
Machine.add( "../EFFECTS/STDIGITC.ck");
Machine.add( "../EFFECTS/STFADEIN.ck");
Machine.add( "../EFFECTS/STFADEOUT.ck");
Machine.add( "../EFFECTS/STFILTERMOD.ck");
Machine.add( "../EFFECTS/STBREAK.ck");
Machine.add( "../EFFECTS/STADSRC.ck");
Machine.add( "../EFFECTS/STABSATURATOR.ck");
Machine.add( "../EFFECTS/STMIX.ck");
Machine.add( "../EFFECTS/STMULT_BASE_ONE.ck");
Machine.add( "../EFFECTS/STMULT_BASE_ZERO.ck");
Machine.add( "../EFFECTS/STADSR.ck");
Machine.add( "../EFFECTS/STPADSR.ck");
Machine.add( "../EFFECTS/STSYNCLPF.ck");
Machine.add( "../EFFECTS/STSYNCLPF2.ck");
Machine.add( "../EFFECTS/STSYNCBPF.ck");
Machine.add( "../EFFECTS/STSYNCHPF.ck");
Machine.add( "../EFFECTS/STSYNCBRF.ck");
Machine.add( "../EFFECTS/STSYNCRES.ck");
Machine.add( "../EFFECTS/STSYNCWPDiodeLadder.ck");
Machine.add( "../EFFECTS/STSYNCWPKorg35.ck");
Machine.add( "../EFFECTS/STRECCONV.ck");
Machine.add( "../EFFECTS/STTREMOLO.ck");
Machine.add( "../EFFECTS/STCOMPRESSOR.ck");
Machine.add( "../EFFECTS/STLIMITER.ck");
Machine.add( "../EFFECTS/STGVERB.ck");
Machine.add( "../EFFECTS/STFLANGER.ck");
Machine.add( "../EFFECTS/STEPC.ck");
me.yield();
Machine.add( "../LONG_WAV/LONG_WAV.ck");
Machine.add( "../LONG_WAV/LOOP_WAV.ck");
Machine.add( "../LONG_WAV/LOOP_DOUBLE_WAV.ck");
Machine.add( "../EFFECTS/REV2.ck");
//Machine.add("../seq_2/FREQ_STR.ck");
//Machine.add("../seq_2/SEQ_STR.ck");
Machine.add( "../seq_3/SEQ.ck");
Machine.add( "../seq_3/TONE.ck");
Machine.add( "../NANOKONTROL/NANO_CONTROLER.ck");
Machine.add( "../launchpad/LAUNCHPAD_CONTROLER.ck");
Machine.add( "../lpd8/LPD8_CONTROLLER.ck");
Machine.add( "../KBCONTROLLER/KBCONTROLLER.ck");
Machine.add( "../ledstrip/ledstrip.ck");

// Composite SYNTs
Machine.add("../SYNT/CELLO1.ck");
Machine.add("../SYNT/CELLO2.ck");
Machine.add("../SYNT/CELLO3.ck");
Machine.add("../SYNT/CHORUSA0.ck");
Machine.add("../SYNT/CHORUSA1.ck");
Machine.add("../SYNT/CHORUSA2.ck");

me.yield();
Machine.add("../EFFECTS/STREV2.ck");
Machine.add( "../include/HW.ck");
Machine.add( "../seq_3/SET_WAV.ck");
Machine.add( "../seq_3/SET_WAV2.ck");
Machine.add("../EFFECTS/ARP.ck");
Machine.add("../EFFECTS/STCUTTER.ck");
me.yield();
Machine.add( "../launchpad/script_launcher.ck");
Machine.add("config.ck");
me.yield();
