#!/bin/bash

cp techno_hell/rootpath.ck aapology/
cp techno_hell/rootpath.ck ayawaska/
cp techno_hell/rootpath.ck BASESONG/
cp techno_hell/rootpath.ck bigsynt_audio/
cp techno_hell/rootpath.ck bigsynt_silent/
cp techno_hell/rootpath.ck bollywood_DnB/
cp techno_hell/rootpath.ck bulgrit/
cp techno_hell/rootpath.ck convolution_test/
cp techno_hell/rootpath.ck costa_dub/
cp techno_hell/rootpath.ck debug_mantra/
cp techno_hell/rootpath.ck deep_glass/
cp techno_hell/rootpath.ck dhoomtala_chill/
cp techno_hell/rootpath.ck dither_test/
cp techno_hell/rootpath.ck drum_kit_test/
cp techno_hell/rootpath.ck dub0/
cp techno_hell/rootpath.ck dub1/
cp techno_hell/rootpath.ck dub2/
cp techno_hell/rootpath.ck dub3_bouef/
cp techno_hell/rootpath.ck ederlezi/
cp techno_hell/rootpath.ck flute_trainer/
cp techno_hell/rootpath.ck glitch/
cp techno_hell/rootpath.ck HXC_BASESONG/
cp techno_hell/rootpath.ck ibniz_demo/
cp techno_hell/rootpath.ck inawah/
cp techno_hell/rootpath.ck indian_kid/
cp techno_hell/rootpath.ck intro_tempura/
cp techno_hell/rootpath.ck kudumbao/
cp techno_hell/rootpath.ck mantra/
cp techno_hell/rootpath.ck mantra_old/
cp techno_hell/rootpath.ck melangeator_test/
cp techno_hell/rootpath.ck mongolian_step/
cp techno_hell/rootpath.ck noize/
cp techno_hell/rootpath.ck old_dhoomtala_chill/
cp techno_hell/rootpath.ck old_inawah/
cp techno_hell/rootpath.ck old_intro_ayawuaska/
cp techno_hell/rootpath.ck old_oneplanet/
cp techno_hell/rootpath.ck old_quasar/
cp techno_hell/rootpath.ck oneplanet/
cp techno_hell/rootpath.ck pousse_pousse/
cp techno_hell/rootpath.ck psydub/
cp techno_hell/rootpath.ck quasar/
cp techno_hell/rootpath.ck sangba/
cp techno_hell/rootpath.ck somthing_blue/
cp techno_hell/rootpath.ck song0/
cp techno_hell/rootpath.ck song1/
cp techno_hell/rootpath.ck song10/
cp techno_hell/rootpath.ck song11/
cp techno_hell/rootpath.ck song12/
cp techno_hell/rootpath.ck song13/
cp techno_hell/rootpath.ck song14/
cp techno_hell/rootpath.ck song15/
cp techno_hell/rootpath.ck song16/
cp techno_hell/rootpath.ck song17/
cp techno_hell/rootpath.ck song18/
cp techno_hell/rootpath.ck song19/
cp techno_hell/rootpath.ck song2/
cp techno_hell/rootpath.ck song20/
cp techno_hell/rootpath.ck song21/
cp techno_hell/rootpath.ck song23/
cp techno_hell/rootpath.ck song25/
cp techno_hell/rootpath.ck song26/
cp techno_hell/rootpath.ck song27/
cp techno_hell/rootpath.ck song28/
cp techno_hell/rootpath.ck song3/
cp techno_hell/rootpath.ck song4/
cp techno_hell/rootpath.ck song5/
cp techno_hell/rootpath.ck song6/
cp techno_hell/rootpath.ck song7/
cp techno_hell/rootpath.ck song8/
cp techno_hell/rootpath.ck song9/
cp techno_hell/rootpath.ck spaceCraft/
cp techno_hell/rootpath.ck tek0/
cp techno_hell/rootpath.ck tek1/
cp techno_hell/rootpath.ck test_modes/
cp techno_hell/rootpath.ck test_seq_sync/
cp techno_hell/rootpath.ck test_seq_sync2/
cp techno_hell/rootpath.ck test_sync_midi/
cp techno_hell/rootpath.ck trance/
cp techno_hell/rootpath.ck trance2/
cp techno_hell/rootpath.ck trance2_perf/
cp techno_hell/rootpath.ck trance2_perf2/
cp techno_hell/rootpath.ck trance_jam_satan_012018/
cp techno_hell/rootpath.ck trippy_cat/
cp techno_hell/rootpath.ck VaporBass/

